title: Will Kochanski
email: wk@cs.brown.edu
description: >
    Confused mathematics and computer science undergraduate at Brown University.
baseurl: ""
url: "http://wkochanski.com"
twitter_username: wspkochanski
github_username:  wspk

markdown: kramdown
